---
title: "7001 data cleaning"
output: html_document
date: '2022-05-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#Import the mathdata

```{r cars}
library(tidyverse)
library(psych)
mathdata<-read.csv("/Users/zhangjiping/Desktop/Medicalpremium.csv")
print(mathdata)
head(mathdata)
str(mathdata)
summary(mathdata)
describe(mathdata)
```

#Check inconsistent data(character)

```{r pressure, echo=FALSE}
unique(mathdata$Age )
unique(mathdata$Diabetes)
unique(mathdata$BloodPressureProblems)
unique(mathdata$AnyTransplants)
unique(mathdata$AnyChronicDiseases)
unique(mathdata$Height)
unique(mathdata$Weight)
unique(mathdata$KnownAllergies)
unique(mathdata$HistoryOfCancerInFamily)
unique(mathdata$NumberOfMajorSurgeries)
unique(mathdata$PremiumPrice)
```

#Change data type

```{r}
mathdata$Age<-as.numeric(mathdata$Age)
mathdata$Diabetes <- as.numeric(mathdata$Diabetes)
mathdata$AnyTransplants <- as.numeric(mathdata$AnyTransplants)
mathdata$AnyChronicDiseases <- as.numeric(mathdata$AnyChronicDiseases)
mathdata$Height <- as.numeric(mathdata$Height)
mathdata$Weight <- as.numeric(mathdata$Weight)
mathdata$KnownAllergies <- as.numeric(mathdata$KnownAllergies)
mathdata$HistoryOfCancerInFamily <- as.numeric(mathdata$HistoryOfCancerInFamily)
mathdata$NumberOfMajorSurgeries <- as.numeric(mathdata$NumberOfMajorSurgeries)
mathdata$PremiumPrice <- as.numeric(mathdata$PremiumPrice)
mathdata$BloodPressureProblems <- as.numeric(mathdata$BloodPressureProblems)
```

#boxplot outlier

```{r}
boxplot(mathdata)

```

#Check for missing data

```{r}
anyNA(mathdata)
sum(is.na(mathdata))
##List number of missing data in column
colSums(is.na(mathdata))
# List rows with missing data
missingdata <- mathdata[!complete.cases(mathdata), ]
sum(is.na(missingdata))
```

#Ientify duplicate row

```{r}
duplicated(mathdata)
sum(duplicated(mathdata))
```

#delete duplicate rows

```{r}
mathdata<-mathdata %>% distinct()
sum(duplicated(mathdata))
print(mathdata)
```

#remove invalid values

```{r}
mathdata<-mathdata[complete.cases(mathdata[,7:11]),]
mathdata<-mathdata[complete.cases(mathdata[,2:5]),]
missingdata <- mathdata[!complete.cases(mathdata), ]

sum(is.na(missingdata))
```

#delete outlier

```{r}
data=filter(mathdata,mathdata$BloodPressureProblems<'2'&mathdata$AnyTransplants<'2'&mathdata$AnyChronicDiseases<'2'&mathdata$BloodPressureProblems<'2'&mathdata$Height<'250')
print(data)
mathdata<-data

```

#Median imputation for numerical data & Mode imputation for categorical data

```{r}
mathdata.impute <- mathdata
for (i in which(sapply(mathdata.impute, is.numeric))){
  mathdata.impute[is.na(mathdata.impute[, i]), i] <- median(mathdata.impute[ , i], na.rm = TRUE)
}
```

#Convert INR to MYR

```{r}
mathdata.impute$PremiumPrice<-mathdata.impute$PremiumPrice*0.0563
print(mathdata.impute)
```

#Observe invalid values

```{r}
describe(mathdata.impute)
sum(is.na(mathdata.impute))
```

#view mathdata.impute

```{r}
View(mathdata.impute)
```
